"""
Django settings for django_matchmaker project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from django.conf import settings

if not settings.DEBUG:
    # Build paths inside the project like this: BASE_DIR / 'subdir'.
    BASE_DIR = Path(__file__).resolve().parent.parent.parent


    # Quick-start development settings - unsuitable for production
    # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = 'fRC#JU^DL_zSwzR->lP-d<R/Pt4Ixso&nhZi#K/cbJe~SRP&T9'

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = False

    ADMINS = [
        ('Jianming Chen', 'loafbaker@hotmail.com'),
    ]

    ALLOWED_HOSTS = ['example.com', 'www.example.com']
    # purchasing domain name http://name.com


    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_HOST_USER = 'yourgmail@gmail.com'
    EMAIL_HOST_PASSWORD = 'yourpassword'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True

    ''' 
    If using gmail, you will need to
    unlock Captcha to enable Django 
    to  send for you:
    https://accounts.google.com/displayunlockcaptcha
    '''



    # Application definition

    INSTALLED_APPS = [
        'registration',         # should be immediately above 'django.contrib.admin'
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        # third party apps
        'crispy_forms',
        'crispy_bootstrap3',
        'localflavor',
        # my apps
        'jobs',
        'likes',
        'matches',
        'newsletter',
        'profiles',
        'questions',
    ]

    MIDDLEWARE = [
        'django.middleware.security.SecurityMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
    ]

    ROOT_URLCONF = 'django_matchmaker.urls'

    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [BASE_DIR / 'templates'],
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                ],
            },
        },
    ]

    WSGI_APPLICATION = 'django_matchmaker.wsgi.application'


    # Database
    # https://docs.djangoproject.com/en/5.2/ref/settings/#databases

    from .db_password import DBPASS

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': "mvpland",
            'USER': "cfedeploy",
            'PASSWORD': DBPASS,
        }
    }


    # Password validation
    # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

    AUTH_PASSWORD_VALIDATORS = [
        {
            'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
    ]


    # Internationalization
    # https://docs.djangoproject.com/en/5.2/topics/i18n/

    LANGUAGE_CODE = 'en-us'

    TIME_ZONE = 'UTC'

    USE_I18N = True

    USE_TZ = True


    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/5.2/howto/static-files/

    STATIC_URL = 'static/'

    STATIC_ROOT = '/home/webapps/mvpland_static/'  # BASE_DIR / 'static_in_env' / 'static_root'

    STATICFILES_DIRS = [
        BASE_DIR / 'static_in_pro' / 'our_static',
        # BASE_DIR / 'static_in_env'
    ]

    MEDIA_URL = 'media/'

    MEDIA_ROOT = '/home/webapps/mvpland_media/'  # BASE_DIR / 'static_in_env' / 'media_root'

    # Crispy FORM TAGs SETTINGS

    CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap3'

    CRISPY_TEMPLATE_PACK = 'bootstrap3'

    # DJANGO REGISTRATION REDUX SETTINGS
    ACCOUNT_ACTIVATION_DAYS = 7
    REGISTRATION_AUTO_LOGIN = True
    LOGIN_REDIRECT_URL = '/'

    # Default primary key field type
    # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

    DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
